# Blender Manifest for EXT_bmesh_encoding Addon

schema_version = "1.0.0"

# Addon Information
id = "ext_bmesh_encoding"
version = "1.0.0"
name = "EXT_bmesh_encoding"
tagline = "Preserve mesh topology during glTF export/import"
maintainer = "EXT_bmesh_encoding Team"
type = "add-on"

# Blender Compatibility
blender_version_min = "4.0.0"

# Description
description = """
EXT_bmesh_encoding preserves mesh topology during glTF export/import operations.

This addon implements the EXT_bmesh_encoding glTF extension to maintain
original mesh face structures (quads, ngons) instead of triangulating
during the export/import process.

Features:
- Preserve quad faces during glTF roundtrip
- Maintain ngon topology
- Support for complex mesh structures
- Compatible with VRM 0.x and 1.x formats
"""

# Tags
tags = ["Import-Export", "Mesh", "glTF", "VRM"]

# License
license = ["MIT"]

# Website
website = ""

# Permissions (none required)
# permissions = []

# Addon files
wheels = []

# No external Python modules required beyond Blender's standard library
